cameras = {}
scene = bpy.context.scene
frame = scene.frame_current - 1

# new frame
scene.frame_set(1 + frame)
# new frame
scene.frame_set(2 + frame)
# new frame
scene.frame_set(3 + frame)
# new frame
scene.frame_set(4 + frame)
# new frame
scene.frame_set(5 + frame)
# new frame
scene.frame_set(6 + frame)
# new frame
scene.frame_set(7 + frame)
# new frame
scene.frame_set(8 + frame)
# new frame
scene.frame_set(9 + frame)
# new frame
scene.frame_set(10 + frame)
# new frame
scene.frame_set(11 + frame)
# new frame
scene.frame_set(12 + frame)
# new frame
scene.frame_set(13 + frame)
# new frame
scene.frame_set(14 + frame)
# new frame
scene.frame_set(15 + frame)
# new frame
scene.frame_set(16 + frame)
# new frame
scene.frame_set(17 + frame)
# new frame
scene.frame_set(18 + frame)
# new frame
scene.frame_set(19 + frame)
# new frame
scene.frame_set(20 + frame)
# new frame
scene.frame_set(21 + frame)
# new frame
scene.frame_set(22 + frame)
# new frame
scene.frame_set(23 + frame)
# new frame
scene.frame_set(24 + frame)
# new frame
scene.frame_set(25 + frame)
# new frame
scene.frame_set(26 + frame)
# new frame
scene.frame_set(27 + frame)
# new frame
scene.frame_set(28 + frame)
# new frame
scene.frame_set(29 + frame)
# new frame
scene.frame_set(30 + frame)
# new frame
scene.frame_set(31 + frame)
# new frame
scene.frame_set(32 + frame)
# new frame
scene.frame_set(33 + frame)
# new frame
scene.frame_set(34 + frame)
# new frame
scene.frame_set(35 + frame)
# new frame
scene.frame_set(36 + frame)
# new frame
scene.frame_set(37 + frame)
# new frame
scene.frame_set(38 + frame)
# new frame
scene.frame_set(39 + frame)
# new frame
scene.frame_set(40 + frame)
# new frame
scene.frame_set(41 + frame)
# new frame
scene.frame_set(42 + frame)
# new frame
scene.frame_set(43 + frame)
# new frame
scene.frame_set(44 + frame)
# new frame
scene.frame_set(45 + frame)
# new frame
scene.frame_set(46 + frame)
# new frame
scene.frame_set(47 + frame)
# new frame
scene.frame_set(48 + frame)
# new frame
scene.frame_set(49 + frame)
# new frame
scene.frame_set(50 + frame)
# new frame
scene.frame_set(51 + frame)
# new frame
scene.frame_set(52 + frame)
# new frame
scene.frame_set(53 + frame)
# new frame
scene.frame_set(54 + frame)
# new frame
scene.frame_set(55 + frame)
# new frame
scene.frame_set(56 + frame)
# new frame
scene.frame_set(57 + frame)
# new frame
scene.frame_set(58 + frame)
# new frame
scene.frame_set(59 + frame)
# new frame
scene.frame_set(60 + frame)
# new frame
scene.frame_set(61 + frame)
# new frame
scene.frame_set(62 + frame)
# new frame
scene.frame_set(63 + frame)
# new frame
scene.frame_set(64 + frame)
# new frame
scene.frame_set(65 + frame)
# new frame
scene.frame_set(66 + frame)
# new frame
scene.frame_set(67 + frame)
# new frame
scene.frame_set(68 + frame)
# new frame
scene.frame_set(69 + frame)
# new frame
scene.frame_set(70 + frame)
# new frame
scene.frame_set(71 + frame)
# new frame
scene.frame_set(72 + frame)
# new frame
scene.frame_set(73 + frame)
# new frame
scene.frame_set(74 + frame)
# new frame
scene.frame_set(75 + frame)
# new frame
scene.frame_set(76 + frame)
# new frame
scene.frame_set(77 + frame)
# new frame
scene.frame_set(78 + frame)
# new frame
scene.frame_set(79 + frame)
# new frame
scene.frame_set(80 + frame)
# new frame
scene.frame_set(81 + frame)
# new frame
scene.frame_set(82 + frame)
# new frame
scene.frame_set(83 + frame)
# new frame
scene.frame_set(84 + frame)
# new frame
scene.frame_set(85 + frame)
# new frame
scene.frame_set(86 + frame)
# new frame
scene.frame_set(87 + frame)
# new frame
scene.frame_set(88 + frame)
# new frame
scene.frame_set(89 + frame)
# new frame
scene.frame_set(90 + frame)
# new frame
scene.frame_set(91 + frame)
# new frame
scene.frame_set(92 + frame)
# new frame
scene.frame_set(93 + frame)
# new frame
scene.frame_set(94 + frame)
# new frame
scene.frame_set(95 + frame)
# new frame
scene.frame_set(96 + frame)
# new frame
scene.frame_set(97 + frame)
# new frame
scene.frame_set(98 + frame)
# new frame
scene.frame_set(99 + frame)
# new frame
scene.frame_set(100 + frame)
# new frame
scene.frame_set(101 + frame)
# new frame
scene.frame_set(102 + frame)
# new frame
scene.frame_set(103 + frame)
# new frame
scene.frame_set(104 + frame)
# new frame
scene.frame_set(105 + frame)
# new frame
scene.frame_set(106 + frame)
# new frame
scene.frame_set(107 + frame)
# new frame
scene.frame_set(108 + frame)
# new frame
scene.frame_set(109 + frame)
# new frame
scene.frame_set(110 + frame)
# new frame
scene.frame_set(111 + frame)
# new frame
scene.frame_set(112 + frame)
# new frame
scene.frame_set(113 + frame)
# new frame
scene.frame_set(114 + frame)
# new frame
scene.frame_set(115 + frame)
# new frame
scene.frame_set(116 + frame)
# new frame
scene.frame_set(117 + frame)
# new frame
scene.frame_set(118 + frame)
# new frame
scene.frame_set(119 + frame)
# new frame
scene.frame_set(120 + frame)
# new frame
scene.frame_set(121 + frame)
# new frame
scene.frame_set(122 + frame)
# new frame
scene.frame_set(123 + frame)
# new frame
scene.frame_set(124 + frame)
# new frame
scene.frame_set(125 + frame)
# new frame
scene.frame_set(126 + frame)
# new frame
scene.frame_set(127 + frame)
# new frame
scene.frame_set(128 + frame)
# new frame
scene.frame_set(129 + frame)
# new frame
scene.frame_set(130 + frame)
# new frame
scene.frame_set(131 + frame)
# new frame
scene.frame_set(132 + frame)
# new frame
scene.frame_set(133 + frame)
# new frame
scene.frame_set(134 + frame)
# new frame
scene.frame_set(135 + frame)
# new frame
scene.frame_set(136 + frame)
# new frame
scene.frame_set(137 + frame)
# new frame
scene.frame_set(138 + frame)
# new frame
scene.frame_set(139 + frame)
# new frame
scene.frame_set(140 + frame)
# new frame
scene.frame_set(141 + frame)
# new frame
scene.frame_set(142 + frame)
# new frame
scene.frame_set(143 + frame)
# new frame
scene.frame_set(144 + frame)
# new frame
scene.frame_set(145 + frame)
# new frame
scene.frame_set(146 + frame)
# new frame
scene.frame_set(147 + frame)
# new frame
scene.frame_set(148 + frame)
# new frame
scene.frame_set(149 + frame)
# new frame
scene.frame_set(150 + frame)
# new frame
scene.frame_set(151 + frame)
# new frame
scene.frame_set(152 + frame)
# new frame
scene.frame_set(153 + frame)
# new frame
scene.frame_set(154 + frame)
# new frame
scene.frame_set(155 + frame)
# new frame
scene.frame_set(156 + frame)
# new frame
scene.frame_set(157 + frame)
# new frame
scene.frame_set(158 + frame)
# new frame
scene.frame_set(159 + frame)
# new frame
scene.frame_set(160 + frame)
# new frame
scene.frame_set(161 + frame)
# new frame
scene.frame_set(162 + frame)
# new frame
scene.frame_set(163 + frame)
# new frame
scene.frame_set(164 + frame)
# new frame
scene.frame_set(165 + frame)
# new frame
scene.frame_set(166 + frame)
# new frame
scene.frame_set(167 + frame)
# new frame
scene.frame_set(168 + frame)
# new frame
scene.frame_set(169 + frame)
# new frame
scene.frame_set(170 + frame)
# new frame
scene.frame_set(171 + frame)
# new frame
scene.frame_set(172 + frame)
# new frame
scene.frame_set(173 + frame)
# new frame
scene.frame_set(174 + frame)
# new frame
scene.frame_set(175 + frame)
# new frame
scene.frame_set(176 + frame)
# new frame
scene.frame_set(177 + frame)
# new frame
scene.frame_set(178 + frame)
# new frame
scene.frame_set(179 + frame)
# new frame
scene.frame_set(180 + frame)
# new frame
scene.frame_set(181 + frame)
# new frame
scene.frame_set(182 + frame)
# new frame
scene.frame_set(183 + frame)
# new frame
scene.frame_set(184 + frame)
# new frame
scene.frame_set(185 + frame)
# new frame
scene.frame_set(186 + frame)
# new frame
scene.frame_set(187 + frame)
# new frame
scene.frame_set(188 + frame)
# new frame
scene.frame_set(189 + frame)
# new frame
scene.frame_set(190 + frame)
# new frame
scene.frame_set(191 + frame)
# new frame
scene.frame_set(192 + frame)
# new frame
scene.frame_set(193 + frame)
# new frame
scene.frame_set(194 + frame)
# new frame
scene.frame_set(195 + frame)
# new frame
scene.frame_set(196 + frame)
# new frame
scene.frame_set(197 + frame)
# new frame
scene.frame_set(198 + frame)
# new frame
scene.frame_set(199 + frame)
# new frame
scene.frame_set(200 + frame)
# new frame
scene.frame_set(201 + frame)
# new frame
scene.frame_set(202 + frame)
# new frame
scene.frame_set(203 + frame)
# new frame
scene.frame_set(204 + frame)
# new frame
scene.frame_set(205 + frame)
# new frame
scene.frame_set(206 + frame)
# new frame
scene.frame_set(207 + frame)
# new frame
scene.frame_set(208 + frame)
# new frame
scene.frame_set(209 + frame)
# new frame
scene.frame_set(210 + frame)
# new frame
scene.frame_set(211 + frame)
# new frame
scene.frame_set(212 + frame)
# new frame
scene.frame_set(213 + frame)
# new frame
scene.frame_set(214 + frame)
# new frame
scene.frame_set(215 + frame)
# new frame
scene.frame_set(216 + frame)
# new frame
scene.frame_set(217 + frame)
# new frame
scene.frame_set(218 + frame)
# new frame
scene.frame_set(219 + frame)
# new frame
scene.frame_set(220 + frame)
# new frame
scene.frame_set(221 + frame)
# new frame
scene.frame_set(222 + frame)
# new frame
scene.frame_set(223 + frame)
# new frame
scene.frame_set(224 + frame)
# new frame
scene.frame_set(225 + frame)
# new frame
scene.frame_set(226 + frame)
# new frame
scene.frame_set(227 + frame)
# new frame
scene.frame_set(228 + frame)
# new frame
scene.frame_set(229 + frame)
# new frame
scene.frame_set(230 + frame)
# new frame
scene.frame_set(231 + frame)
# new frame
scene.frame_set(232 + frame)
# new frame
scene.frame_set(233 + frame)
# new frame
scene.frame_set(234 + frame)
# new frame
scene.frame_set(235 + frame)
# new frame
scene.frame_set(236 + frame)
# new frame
scene.frame_set(237 + frame)
# new frame
scene.frame_set(238 + frame)
# new frame
scene.frame_set(239 + frame)
# new frame
scene.frame_set(240 + frame)
# new frame
scene.frame_set(241 + frame)
# new frame
scene.frame_set(242 + frame)
# new frame
scene.frame_set(243 + frame)
# new frame
scene.frame_set(244 + frame)
# new frame
scene.frame_set(245 + frame)
# new frame
scene.frame_set(246 + frame)
# new frame
scene.frame_set(247 + frame)
# new frame
scene.frame_set(248 + frame)
# new frame
scene.frame_set(249 + frame)
# new frame
scene.frame_set(250 + frame)
# markers
